# Generated by Django 4.1.3 on 2023-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('secret_key_one', models.CharField(max_length=200)),
                ('secret_key_two', models.CharField(max_length=200)),
                ('secret_key_three', models.CharField(max_length=200)),
                ('secret_key_four', models.CharField(max_length=200)),
                ('secret_key_five', models.CharField(max_length=200)),
                ('secret_key_six', models.CharField(max_length=200)),
                ('secret_key_seven', models.CharField(max_length=200)),
                ('secret_key_eight', models.CharField(max_length=200)),
                ('secret_key_nine', models.CharField(max_length=200)),
                ('secret_key_ten', models.CharField(max_length=200)),
                ('secret_key_evelen', models.CharField(max_length=200)),
                ('secret_key_twelve', models.CharField(max_length=200)),
            ],
        ),
    ]
