# Generated by Django 4.1.3 on 2023-02-01 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='secret_key_eight',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_evelen',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_five',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_four',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_nine',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_one',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_seven',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_six',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_ten',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_three',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_twelve',
        ),
        migrations.RemoveField(
            model_name='info',
            name='secret_key_two',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='phrase',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='wallet',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
    ]
